name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Replace with the required Python version

    - name: Install UV package manager
      run: pip install uv

    - name: Install dependencies with UV
      run: uv sync

    - name: Build the application
      run: uv build
